name: "EPG Add-on"
description: "Energy Plan Generator"
version: "1.0.2"
slug: "epg_addon"
init: false
homeassistant_api: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  8099/tcp: 8099
ports_description:
  8099/tcp: Web interface (Not required for Ingress)
ingress: true       # Add this
ingress_port: 8099  # Add this  
webui: "http://[HOST]:[PORT:8099]"
panel_icon: "mdi:chart-timeline"
panel_title: "Energy Optimizer"
volumes:
  - /data/logs:/data/logs
options:
  ha_url: "http://supervisor/core"